name: Build and deploy JAR app to Azure Web App - springboothelloworld

on:
 workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
  dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
  
    - name: Download artifact from jfrog
      run: |
          curl -u${{ secrets.JFROG_USER}}:${{ secrets.JFROG_PASSWORD}} -O "https://myjfrogregistry2134.jfrog.io/ui/native/java-springboot-app-generic-local/spring-boot-hello-world-1.0.0.jar"
          ls
          ls -l
          whoami
          chmod 777 spring-boot-hello-world-1.0.0.jar
          pwd
    
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
          name: java-app
  
         

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
          app-name: 'springbootdev'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: 'spring-boot-hello-world-1.0.0.jar'
          
 
   
