name: vault

# Controls when the workflow will run
on:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:


jobs:
  build:
 
    runs-on: ubuntu-latest
    steps: 
       - uses: actions/checkout@v2       
       - name: Import Secrets from vault
         uses: hashicorp/vault-action@v2.4.0
         with:
             url: ${{ secrets.VAULT_HOST }}
             method: token
             roleId: ${{ secrets.VAULT_ROLE_ID }}
             secretId: ${{ secrets.VAULT_SECRET_ID }}
             token: ${{ secrets.VAULT_TOKEN }}
             secrets: |
                 secrets/ado/Jfrog-secrets  jfrogusername  | Jfrog-username;
                 secrets/ado/Jfrog-secrets  jfrogpassword  | Jfrog-password
               
                 
                    
#                   vault secrets enable -path=kv kv
#                   vault secrets list
#                   vault kv put kv/hello target=world
#                   vault kv get kv/hello
            
                     
                     
   
                        

