name: vault

# Controls when the workflow will run
on:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:


jobs:
  build:
 
    runs-on: self-hosted
    steps: 
       - uses: actions/checkout@v2       
       - name: Import Secrets from vault
         uses: hashicorp/vault-action@v2.4.0
         with:
             url: ${{ secrets.VAULT_HOST }}
             method: approle
             roleId: ${{ secrets.VAULT_ROLE_ID }}
             secretId: ${{ secrets.VAULT_SECRET_ID }}
             token: ${{ secrets.VAULT_TOKEN }}
             run: |
                  vault secrets enable -path=kv kv
                  vault secrets list
                  vault kv put kv/hello target=world
                  vault kv get kv/hello
            
                     
                     
   
                        

